blank_issues_enabled: false
contact_links:
  - name: 参与讨论 / Join Discussions
    url: https://github.com/TerrorAWM/kebiaov2/discussions
    about: 如果你有问题或想法，欢迎到讨论区交流 | Join discussions for questions and ideas
